# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PassionCommonDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PassionCommonDemo
  pod 'PassionCommon'

  target 'PassionCommonDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PassionCommonDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
